#!/usr/bin/env bash

# Define a variable that takes the user's directory as an argument
# https://expressionengine.com/forums/topic/100411/simple-bash-script-to-create-new-symlinks
user=$1

# This checks if the .bashrc file exists for the user
if [[ -f "$user/.bashrc" ]]; then
	# If the file exists, remove the .bashrc to create a new symlink
	echo "Removing existing .bashrc for user $user..."
	rm $user/.bashrc
else
	echo
	".bashrc does not exist for user $user"
fi

# Creates a symbolic link for the bin directory
# Links /home/$user/copy_config/bin to /home/$user/bin
# Allows user to use the bin directory from copy_config folder
ln -s /home/$user/copy_config/bin /home/$user/bin

# Creates a symbolic link for the config directory
# Links /home/$user/copy_config/config to /home/$user/.config
# Allows user to use the config directory from copy_config folder
ln -s /home/$user/copy_config/config /home/$user/.config

# Creates a symbolic link for the .bashrc file
# Links /home/$user/copy_config/bashrc to /home/$user/.bashrc
# Allows user to use custom .bashrc file from copy_config folder
ln -s /home/$user/copy_config/home/bashrc /home/$user/.bashrc

